algorithm: ppo
eval_episodes: 20
eval_phases: 20
fixed_env_seeds:
- 2
- 3
hyper_params:
  learning_rate: 0.0003
  buffer_size: 1000000
  batch_size: 256
  tau: 0.005
  gamma: 0.99
  learning_starts: 100
  
seeds:
- 0
- 1
- 2
- 3
- 4
steps: 100000
use_fixed_env_seeds: true
ignore_hyper_params: true
