algorithm: ""
eval_episodes: 20
eval_phases: 20
fixed_env_seeds:
- 2
- 3
hyper_params:
  learning_rate: 0.0001
  gamma: 0.99
    
seeds:
- 0
- 1
steps: 400000
use_fixed_env_seeds: true
ignore_hyper_params: true
use_rendering: false
